name = "HauntedArrays"
uuid = "88ea1a40-65ed-4bf4-98f2-fb8783b28482"
authors = ["bmxam <maxime.bouyges@gmail.com>"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIUtils = "d2fda7fa-1d8f-42bf-b3ab-bccc7e8e7842"
