name = "HauntedArrays"
uuid = "88ea1a40-65ed-4bf4-98f2-fb8783b28482"
authors = ["bmxam <maxime.bouyges@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
